name: plus_flutter_app_builder
description: Build your Flutter app via Dart.
version: 0.6.0
homepage: https://github.com/mozomig/fastforge
repository: https://github.com/mozomig/fastforge/tree/main/packages/flutter_app_builder

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  glob: ^2.1.1
  path: ^1.8.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.1.0
  recase: ^4.1.0
  plus_shell_executor: ^0.3.0

dev_dependencies:
  dependency_validator: ^3.0.0
  mostly_reasonable_lints: ^0.1.2
  test: ^1.23.1
