name: plus_shell_executor
description: A simple shell commands executor.
version: 0.3.0
homepage: https://github.com/mozomig/fastforge
repository: https://github.com/mozomig/fastforge/tree/main/packages/shell_executor

environment:
  sdk: ">=2.16.0 <4.0.0"

dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.23.1
