name: flutter_distributor
description: A powerful and efficient tool for packaging and publishing your applications with ease.
version: 0.6.2
homepage: https://fastforge.dev
repository: https://github.com/fastforgedev/fastforge/tree/main/packages/flutter_distributor
issue_tracker: https://github.com/fastforgedev/fastforge/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  unified_distributor: ^0.2.2

dev_dependencies:
  mostly_reasonable_lints: ^0.1.2

executables:
  flutter_distributor: main
