name: plus_unified_distributor
description: A powerful and efficient tool for packaging and publishing your applications with ease.
version: 0.2.7
homepage: https://github.com/mozomig/fastforge
repository: https://github.com/mozomig/fastforge/tree/main/packages/unified_distributor
issue_tracker: https://github.com/mozomig/fastforge/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.2.0
  charset: ^2.0.1
  dio: ^5.3.4
  plus_flutter_app_builder: ^0.6.0
  plus_flutter_app_packager: ^0.6.5
  plus_flutter_app_publisher: ^0.6.7
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.1.0
  plus_shell_executor: ^0.3.0
  plus_shell_uikit: ^0.3.0
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
  mostly_reasonable_lints: ^0.1.2
  test: ^1.23.1
